env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx : true
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
globals:
  # ignore these global vars from outside
  _config: readonly
  _play: readonly
  $: readonly